server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /healthz { add_header Content-Type text/plain; return 200 "ok"; }

  location /lab/ {
    try_files $uri $uri/ /lab/index.html;
  }

  location /studio/ {
    try_files $uri $uri/ /studio/index.html;
  }

  location = / {
    try_files /landing/index.html =404;
  }

  location / {
    try_files $uri $uri/ /landing/index.html;
  }
}
