server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /healthz { add_header Content-Type text/plain; return 200 'ok'; }

  # Lab — Angular SPA
  location /lab/ {
    try_files $uri $uri/ /lab/index.html;
  }

  # Studio — Angular SPA
  location /studio/ {
    try_files $uri $uri/ /studio/index.html;
  }

  # Landing page — static
  location / {
    try_files $uri $uri/ =404;
  }
}
