import { CatalogEntry } from './catalog-entry.model';

export const CATALOG_ENTRIES: CatalogEntry[] = [
  { slug: 'accordion', label: 'Accordion', status: 'verified', icon: 'layers' },
  { slug: 'alert', label: 'Alert', status: 'verified', icon: 'alert-triangle' },
  { slug: 'attachments', label: 'Allegati', status: 'verified', icon: 'paperclip' },
  { slug: 'motion', label: 'Animazioni', status: 'verified', icon: 'play' },
  { slug: 'avatar', label: 'Avatar', status: 'verified', icon: 'user' },
  { slug: 'tags-badges', label: 'Badge & Chip', status: 'verified', icon: 'tag' },
  { slug: 'banner', label: 'Banner', status: 'verified', icon: 'window' },
  { slug: 'navbar', label: 'Barra di navigazione', status: 'verified', icon: 'menu' },
  { slug: 'breadcrumb', label: 'Breadcrumb', status: 'verified', icon: 'link' },
  { slug: 'form-field', label: 'Campi e Moduli', status: 'verified', icon: 'document' },
  { slug: 'checkbox', label: 'Caselle di controllo', status: 'verified', icon: 'check' },
  { slug: 'examples', label: 'Esempi', status: 'verified', icon: 'view' },
  { slug: 'layout', label: 'Layout', status: 'verified', icon: 'sidebar' },
  { slug: 'dialog', label: 'Modal & Dialoghi', status: 'verified', icon: 'window' },
  { slug: 'pagination', label: 'Paginazione', status: 'verified', icon: 'bar-chart' },
  { slug: 'panel', label: 'Panel', status: 'verified', icon: 'sidebar' },
  { slug: 'patterns', label: 'Pattern e governance', status: 'verified', icon: 'layers' },
  { slug: 'popover', label: 'Popover', status: 'verified', icon: 'message-circle' },
  { slug: 'button', label: 'Pulsanti', status: 'verified', icon: 'square' },
  { slug: 'pill-switch', label: 'Selettore a pillola', status: 'verified', icon: 'toggle' },
  { slug: 'date-picker', label: 'Selettore Data', status: 'verified', icon: 'calendar' },
  { slug: 'time-picker', label: 'Selettore Ora', status: 'verified', icon: 'clock' },
  { slug: 'select', label: 'Selezione', status: 'verified', icon: 'chevron-down' },
  { slug: 'skeleton', label: 'Skeleton', status: 'verified', icon: 'square' },
  { slug: 'slider', label: 'Slider', status: 'verified', icon: 'slider' },
  { slug: 'spinner', label: 'Spinner', status: 'verified', icon: 'retry' },
  { slug: 'tooltip', label: 'Suggerimenti', status: 'verified', icon: 'info' },
  { slug: 'tab', label: 'Tab', status: 'verified', icon: 'layers' },
  { slug: 'table', label: 'Table', status: 'verified', icon: 'grid' },
  { slug: 'themes', label: 'Temi e superfici', status: 'verified', icon: 'settings' },
  { slug: 'typography', label: 'Tipografia', status: 'verified', icon: 'document' },
  { slug: 'toast', label: 'Toast', status: 'verified', icon: 'message-circle' },
];
